apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring-diyabet
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'diyabet-tahmin-app'
        static_configs:
          - targets: ['diyabet-tahmin-app-service.default:8001'] # default namespace’ten erişim